"""Evidence-backed metadata for the public technical project library."""

from __future__ import annotations


LABELS = {
    "implemented": "Code-derived architecture",
    "prototype": "Source-backed prototype",
    "deterministic": "Deterministic / AI-enabling",
    "concept": "Documentation-only source",
}


def p(*, slug, name, archive, category, level, summary, ai_role, stack, skills, flow,
      services, ai, data, operations, evidence, controls=None, outputs=None,
      experience=None, thesis=None, roadmap=None):
    outputs = outputs or [flow[-1], "Evidence-backed result", "Human review", "Operational action"]
    experience = experience or [flow[0], outputs[0], outputs[1]]
    controls = controls or [
        "Least-privilege configuration",
        "Input and output validation",
        "Traceable execution evidence",
        "Human-owned decisions",
    ]
    roadmap = roadmap or skills[:4]
    return {
        "slug": slug,
        "name": name,
        "archive": archive,
        "category": category,
        "evidence_level": level,
        "evidence_label": LABELS[level],
        "summary": summary,
        "ai_role": ai_role,
        "stack": stack,
        "skills": skills,
        "flow": flow,
        "components": {
            "experience": experience,
            "services": services,
            "ai": ai,
            "data": data,
            "operations": operations,
        },
        "controls": controls,
        "outputs": outputs,
        "architecture_thesis": thesis or summary,
        "evidence": evidence,
        "roadmap": roadmap,
    }


PROJECTS = [
    p(
        slug="profitability", name="Project Profitability Intelligence", archive="Profitability.zip",
        category="Data & decision intelligence", level="prototype",
        summary="Monthly revenue, cost, margin, FTE and concentration analytics with a grounded finance-assistant layer.",
        ai_role="Deterministic analysis plus selectable local and hosted LLM adapters over scoped dashboard context; the public package removes the embedded credential and real financial snapshots.",
        stack=["React", "Vite", "Node.js", "Microsoft Graph", "Docker", "Nginx", "Jenkins"],
        skills=["Financial analytics", "Grounded prompting", "Provider abstraction", "Graph OAuth", "Snapshot governance", "CI/CD"],
        flow=["Monthly finance package", "Graph synchronizer", "Sanitized snapshot store", "Profitability dashboard", "Grounded AI context", "Decision narrative"],
        services=["Policy-aware sync", "Dashboard application", "Finance context builder", "Provider adapter"],
        ai=["Deterministic finance rules", "Local Ollama path", "Hosted LLM adapters", "Grounding and refusal"],
        data=["SharePoint package", "Monthly snapshots", "Account/project measures"],
        operations=["Nginx", "Docker Compose", "Jenkins pipeline", "Health checks"],
        evidence=["README.md", "tools/sync-dashboard.mjs", "tools/guard.js", "nginx.conf", "infra/Jenkinsfile"],
        controls=["No browser-embedded API keys", "Synthetic public finance data", "Employee-scope filtering", "Provider/CSP boundary"],
    ),
    p(
        slug="zeno-injector", name="Zeno RAG Ingestion Platform", archive="Prod_Data_Injection.zip",
        category="Knowledge, RAG & document AI", level="implemented",
        summary="Production document ingestion with multimodal parsing, governed chunking, embeddings and ACL-aware vector persistence.",
        ai_role="Qwen embedding and vision services transform structured and scanned documents into retrieval-ready chunks while enforcing embedding parity and metadata contracts.",
        stack=["Python", "FastAPI", "Milvus", "PostgreSQL", "LlamaIndex", "MinIO", "Prometheus", "OpenShift"],
        skills=["RAG ingestion", "Multimodal OCR", "Vector schema governance", "ACL propagation", "Idempotent orchestration", "Observability"],
        flow=["Enterprise documents", "Discovery and diff", "Parser / OCR router", "Token-aware chunker", "Embedding gateway", "Milvus collection"],
        services=["Source adapters", "Recovery ledger", "Parser router", "Chunking orchestrator", "Ops API"],
        ai=["Qwen3 embeddings", "Qwen3-VL OCR", "Structure-aware chunking", "Embedding parity checks"],
        data=["Document references", "PostgreSQL ledger", "Milvus vectors", "Optional object store"],
        operations=["FastAPI health plane", "Prometheus", "Docker", "OpenShift / Jenkins"],
        evidence=["ARCHITECTURE.md", "src/zeno_injector/orchestrator/run.py", "src/zeno_injector/parsing/router.py", "src/zeno_injector/processing/chunker.py", "src/zeno_injector/store/milvus_sink.py"],
        controls=["ACL metadata preserved", "Delete guard and idempotency", "Embedding contract validation", "Recovery ledger and metrics"],
    ),
    p(
        slug="paperclip-ai", name="Paperclip AI", archive="Paperclip AI.zip",
        category="Concept / source unavailable", level="concept",
        summary="The supplied archive contains only an untouched project-template README; no implementation evidence was available.",
        ai_role="No model, agent, retrieval, automation or application code is present. Architecture views are explicitly conceptual evidence-gap maps.",
        stack=["Source unavailable"], skills=["No verifiable technical skills in supplied archive"],
        flow=["Project intent", "Missing source", "Evidence request", "Architecture definition", "Implementation", "Validation"],
        services=["Implementation not supplied"], ai=["No runtime AI evidenced"], data=["No data model supplied"], operations=["No deployment evidence supplied"],
        evidence=["README.md"],
        controls=["Concept label", "No fabricated implementation claims", "No runnable status claim", "Request complete source"],
    ),
    p(
        slug="oneview", name="OneView Customer & Project Intelligence", archive="Oneview.zip",
        category="Data & decision intelligence", level="implemented",
        summary="A multi-service account 360, adoption, project-health and executive reporting platform with grounded AI narratives.",
        ai_role="Scoped customer and portfolio context feeds internal and hosted model services for summaries, risks, actions and adoption narratives with caching and deterministic health scoring.",
        stack=["Python", "FastAPI", "React", "Vite", "SQLite", "OpenAI API", "Nginx", "Docker"],
        skills=["Multi-service analytics", "Grounded AI", "Multimodal analysis", "Prompt governance", "Report automation", "RBAC"],
        flow=["Enterprise sources", "Refresh pipelines", "JSON / SQLite stores", "Three application services", "Grounded LLM gateway", "Executive reports"],
        services=["OneView portal", "Project-health API", "Adoption analytics API", "Report generator"],
        ai=["Cross-dashboard assistant", "Portfolio risk narratives", "Adoption insight generation", "PDF-page vision analysis"],
        data=["CRM and delivery extracts", "Finance/adoption metrics", "SQLite cache", "Sanitized account model"],
        operations=["Nginx gateway", "Docker Compose", "Scheduled refresh", "Jenkins deployment"],
        evidence=["scripts/build_data.py", "scripts/summary.py", "adoption-analytics/backend/insights.py", "adoption-analytics/backend/qbr_report.py", "coe-dashboard/main.py"],
        controls=["Scoped context construction", "Insight caching", "Deterministic health baseline", "Customer datasets excluded publicly"],
    ),
    p(
        slug="okr-dashboard", name="AI-Assisted OKR Strategy Dashboard", archive="OKRDashboard.zip",
        category="Data & decision intelligence", level="implemented",
        summary="A balanced-scorecard workspace that combines live OKR measures, strategy maps and streaming executive analysis.",
        ai_role="Role- and period-scoped context is streamed to an OpenAI-compatible model for grounded executive answers and chart specifications.",
        stack=["Python", "Flask", "PostgreSQL", "React", "Vite", "Recharts", "SSE"],
        skills=["OKR analytics", "Streaming AI UX", "Prompt grounding", "Dynamic chart generation", "Connection pooling", "Strategy visualization"],
        flow=["OKR DataMart", "Background synchronizer", "Live metric store", "Dashboard APIs", "Scoped LLM analysis", "Narrative and chart"],
        services=["Metric sync", "Flask API", "Context builder", "SSE response parser"],
        ai=["Intent classification", "Grounded executive Q&A", "Chart-spec generation", "Streaming completion"],
        data=["Balanced-scorecard metrics", "Financial targets", "Role / fiscal filters"],
        operations=["Background refresh", "Connection pool", "Static React build", "Deployment scripts removed"],
        evidence=["TECHNICAL_SPEC.md", "server.py", "dashboard/src/App.jsx", "dashboard/src/components/DeliveryDashboard.jsx"],
        controls=["All original credentials removed", "Scoped metric context", "Structured chart markers", "Public package uses no production host"],
    ),
    p(
        slug="obsidian-llm-wiki", name="Obsidian LLM Wiki & Action Agent", archive="Obsidian_LLM_Wiki.zip",
        category="Agentic AI & automation", level="implemented",
        summary="SharePoint-to-Markdown knowledge retrieval combined with governed, teachable browser automation for enterprise workflows.",
        ai_role="NVIDIA-compatible answering, planning and skill selection operate beside deterministic fallback, human confirmation and trust progression.",
        stack=["TypeScript", "Next.js", "React", "Microsoft Graph", "Playwright", "PostgreSQL", "Docker", "Edge extension"],
        skills=["Enterprise knowledge ingestion", "Agent planning", "Teach-and-replay automation", "HITL", "Trust calibration", "Audit trails"],
        flow=["SharePoint content", "Document extraction", "Markdown vault", "Retrieval and context", "Governed planner", "Browser action evidence"],
        services=["Graph connector", "Extraction pipeline", "Wiki search", "Skill library", "Worker queue"],
        ai=["Cited answer generation", "Multi-step planner", "Skill selection", "Observation-to-skill mining"],
        data=["Markdown vault", "Agent memory", "PostgreSQL state", "Audit events"],
        operations=["Docker / Caddy", "Worker process", "Browser extension", "Approval queue"],
        evidence=["packages/core/src/nim.ts", "packages/core/src/sharepoint.ts", "packages/core/src/planner.ts", "packages/core/src/executor.ts", "packages/core/src/trust.ts"],
        controls=["Stage / dry-run / live progression", "Human confirmation", "Idempotent execution", "Constant-time token checks"],
    ),
    p(
        slug="wsr-automate", name="WSR Automation & Delivery Control Tower", archive="WSR-Automate.zip",
        category="Agentic AI & automation", level="implemented",
        summary="An agent-orchestrated weekly status pipeline producing executive decks, structured reports and governed delivery notifications.",
        ai_role="A structured-analysis model augments deterministic portfolio calculations, while source, analysis, presentation and delivery agents coordinate evidence-backed outputs.",
        stack=["Node.js", "React", "n8n", "PptxGenJS", "ExcelJS", "WebSockets", "Docker", "Azure DevOps"],
        skills=["Agent orchestration", "Executive narrative generation", "Presentation automation", "Forecasting", "Durable learning", "Delivery governance"],
        flow=["Delivery sources", "Parallel source agents", "Deterministic analyzer", "LLM and memory", "PPTX / JSON / XLSX", "Controlled distribution"],
        services=["Agent swarm runner", "Portfolio analyzer", "Presentation generator", "Delivery adapters"],
        ai=["Structured executive analysis", "Forecast and anomaly narratives", "Durable memory", "Graceful deterministic fallback"],
        data=["Work-item evidence", "Delivery metrics", "Learning memory", "Generated report model"],
        operations=["n8n scheduler", "WebSocket control tower", "Email / messaging adapters", "Docker"],
        evidence=["src/agents/swarm-runner.js", "src/services/analyzer.js", "src/hermes/client.js", "src/hermes/memory.js", "src/pptx-generator.js"],
        controls=["Credential-bearing workflows excluded", "Source lineage", "Structured-output repair", "Human-controlled delivery"],
    ),
    p(
        slug="world-monitor", name="World Monitor", archive="WorldMonitor.zip",
        category="Concept / source unavailable", level="concept",
        summary="The archive contains a generic README and workstation sync script, but no monitoring application or AI implementation.",
        ai_role="No runtime intelligence is evidenced. The architecture pack documents the missing evidence and a conceptual monitoring lifecycle only.",
        stack=["Source unavailable"], skills=["No verifiable implementation in supplied archive"],
        flow=["Monitoring intent", "Missing source", "Signal inventory", "Detection design", "Alert workflow", "Operational validation"],
        services=["Implementation not supplied"], ai=["No runtime AI evidenced"], data=["No telemetry model supplied"], operations=["Local sync script excluded"],
        evidence=["README.md", ".git_sync.sh"], controls=["Concept label", "Local path removed", "No auto-push script published", "No production claims"],
    ),
    p(
        slug="whatsapp-bot-monitoring", name="WhatsApp Bot Monitoring & AI Operations", archive="Whatsapp_BOT_Monitoring.zip",
        category="AI testing & quality", level="implemented",
        summary="Synthetic journey monitoring for WhatsApp automation with retries, evidence capture, incident routing and AI-assisted diagnosis.",
        ai_role="A structured insight service summarizes failures and operator questions while deterministic monitoring and fallback logic remain authoritative.",
        stack=["Python", "Flask", "Playwright", "n8n", "JavaScript", "Waitress", "WhatsApp Web"],
        skills=["Synthetic monitoring", "Browser automation", "Retry analysis", "Incident integration", "Operational metrics", "LLM fallback"],
        flow=["n8n schedule", "Monitoring API", "Playwright journey", "Logs and evidence", "AI health analysis", "Incident / dashboard"],
        services=["Journey runner", "Retry controller", "Health engine", "Incident adapter", "Dashboard API"],
        ai=["Failure summaries", "Operator Q&A", "Structured health insights", "Deterministic fallback"],
        data=["Synthetic journey events", "Sanitized logs", "Health metrics", "Incident state"],
        operations=["n8n", "Persistent browser session", "Email / CRM adapters", "Web dashboard"],
        evidence=["Login WhatsApp/monitor.py", "Login WhatsApp/api_server.py", "New project/services/ai_service.py", "New project/services/dashboard_service.py"],
        controls=["Runtime screenshots/logs excluded", "Synthetic contacts only", "Secret redaction", "Authenticated deployment required"],
    ),
    p(
        slug="us-project-health", name="US Project Health Dashboard", archive="USProjecthealth.zip",
        category="Data & decision intelligence", level="deterministic",
        summary="Portfolio-health analytics that reconcile delivery and CRM evidence into weighted red/amber/green outcomes.",
        ai_role="No LLM or retrieval model is present; RAG means deterministic Red/Amber/Green scoring with transparent thresholds and weights.",
        stack=["Python", "FastAPI", "Azure DevOps", "Redash", "Jinja2", "httpx"],
        skills=["Async integration", "Source reconciliation", "Data quality", "Weighted health scoring", "TTL caching", "Graceful degradation"],
        flow=["Delivery and CRM sources", "Parallel fetch", "Alias reconciliation", "Metric engine", "Weighted RAG score", "Portfolio dashboard"],
        services=["Azure Boards client", "Redash client", "Alias resolver", "Project report service"],
        ai=["No runtime AI", "Transparent weighted scoring", "Deterministic thresholds"],
        data=["Work items", "Project metrics", "Health dimensions", "TTL cache"],
        operations=["FastAPI", "Partial-failure handling", "Server-rendered dashboard"],
        evidence=["main.py", "azure_client.py", "redash_client.py", "project_report.py", "rag_engine.py"],
        controls=["No AI overclaim", "Customer mappings excluded", "Deterministic score trace", "No internal topology published"],
    ),
    p(
        slug="skill-management", name="Skill Management", archive="Skillmanagement.zip",
        category="Concept / source unavailable", level="concept",
        summary="The supplied archive is an untouched project-template README with no skill platform implementation.",
        ai_role="No model, recommendation engine, data schema or application code is available for verification.",
        stack=["Source unavailable"], skills=["No verifiable technical skills in supplied archive"],
        flow=["Skills intent", "Missing source", "Taxonomy design", "Evidence model", "Matching engine", "Validation"],
        services=["Implementation not supplied"], ai=["No runtime AI evidenced"], data=["No skills taxonomy supplied"], operations=["No deployment evidence supplied"],
        evidence=["README.md"], controls=["Concept label", "No fabricated matching claims", "No runnable status claim", "Request complete source"],
    ),
    p(
        slug="rmg-bot", name="RMG Resource Allocation Assistant", archive="RMGBOT.zip",
        category="Knowledge, RAG & document AI", level="prototype",
        summary="A local resource-management analytics and conversational allocation assistant grounded in workforce data.",
        ai_role="FAISS retrieval and MiniLM embeddings ground a local Qwen assistant, with structured-query fallbacks for deterministic allocation analysis.",
        stack=["Python", "FastAPI", "LangChain", "FAISS", "SentenceTransformers", "llama.cpp", "pandas", "JavaScript"],
        skills=["Local inference", "RAG indexing", "Resource analytics", "Grounding", "Offline fallback", "Conversational UI"],
        flow=["Synthetic allocation data", "Resource processor", "Chunk and embedding index", "FAISS retrieval", "Local Qwen", "Allocation answer"],
        services=["Data processor", "RAG server", "LLM server", "Dashboard API"],
        ai=["MiniLM embeddings", "FAISS retrieval", "Local Qwen inference", "Rule-based fallback"],
        data=["Synthetic allocations", "KPI aggregates", "Training chunks", "Vector index rebuilt publicly"],
        operations=["FastAPI", "Local CPU/GPU runtime", "Browser dashboard"],
        evidence=["data_processor.py", "rag_server.py", "llm_server.py", "lite_llm_server.py", "app.js"],
        controls=["Employee dataset excluded", "No unsafe pickle index", "Synthetic index only", "Grounded response context"],
    ),
    p(
        slug="rmg-budgeting", name="Resource Allocation & Project Budgeting", archive="RMG_Budgeting.zip",
        category="Enterprise operations", level="deterministic",
        summary="A deterministic resource-planning, burdened-cost, P&L and margin-gated approval system with immutable versions.",
        ai_role="No runtime AI is implemented; intelligence comes from transparent costing, signatures and approval rules rather than an LLM.",
        stack=["React", "TypeScript", "FastAPI", "Python", "PostgreSQL", "Entra OIDC", "Docker", "Excel"],
        skills=["Financial-domain modeling", "Cross-language parity", "Immutable versioning", "Approval workflows", "OIDC/RBAC", "Audit logging"],
        flow=["Budget planner", "Shared rules engine", "Server recomputation", "Signature and margin gate", "PostgreSQL version", "Approval / export"],
        services=["React planning UI", "Shared TypeScript engine", "FastAPI service", "Authoritative Python engine"],
        ai=["No runtime AI", "Deterministic cost engine", "Policy-based approvals"],
        data=["Budget versions", "Resource allocations", "Approval audit", "Directory reference"],
        operations=["Entra OIDC", "Docker", "Excel interchange", "Directory synchronization"],
        evidence=["shared/src/engine.ts", "shared/src/approvalRules.ts", "backend/app/engine.py", "backend/app/schema.sql", "frontend/src/state.ts"],
        controls=["Server-authoritative recomputation", "Signature-bound approval", "Immutable versions", "Customer samples excluded"],
    ),
    p(
        slug="rmg-project360", name="BusinessNext Project360 & Resource Budgeting", archive="RMG.zip",
        category="Enterprise operations", level="deterministic",
        summary="Resource planning and project economics across allocation, burdened cost, P&L, margin gates, approvals and version history.",
        ai_role="No inference model is implemented. Transparent shared rules and a server-authoritative calculation engine supply the decision intelligence.",
        stack=["React", "TypeScript", "Vite", "FastAPI", "Python", "PostgreSQL", "Entra OIDC", "Excel"],
        skills=["Resource planning", "Financial modeling", "Calculation parity", "Immutable versioning", "Approval governance", "Excel interchange"],
        flow=["Planner workspace", "Shared rules engine", "FastAPI validation", "Authoritative recomputation", "Versioned PostgreSQL", "Approval and export"],
        services=["Planning UI", "Budget API", "Cost and margin engine", "Version and approval service"],
        ai=["No runtime AI", "Deterministic fit and margin rules", "Explainable approval gates"],
        data=["Budget versions", "Resource allocations", "Cost assumptions", "Audit history"],
        operations=["Entra OIDC", "Docker", "Directory integration", "Excel import and export"],
        evidence=["Budgeting/shared/src/engine.ts", "Budgeting/backend/app/engine.py", "Budgeting/backend/app/main.py", "Budgeting/backend/app/schema.sql", "Budgeting/backend/app/sso.py"],
        controls=["Server-authoritative calculations", "Version signatures", "RBAC approval gates", "Employee fixtures excluded"],
    ),
    p(
        slug="nps-survey-engine", name="NPS Survey & Workflow Engine", archive="NPS.zip",
        category="Enterprise operations", level="deterministic",
        summary="A full-stack survey platform spanning visual authoring, branching journeys, tokenized response collection, alerts and NPS analytics.",
        ai_role="No model inference is present; scoring, workflow transitions, alert policies and exports are deterministic and auditable.",
        stack=["Next.js", "React", "TypeScript", "Drizzle", "PostgreSQL", "Recharts", "Nodemailer", "Playwright"],
        skills=["Survey systems", "Graph workflows", "NPS analytics", "Email automation", "Tokenized journeys", "Export pipelines"],
        flow=["Survey designer", "Workflow graph", "Next.js API", "PostgreSQL", "Respondent token journey", "Analytics and export"],
        services=["Authoring workspace", "Workflow engine", "Response service", "Mail and alert service"],
        ai=["No runtime AI", "Deterministic NPS scoring", "Rule-based branching and alerts"],
        data=["Survey definitions", "Workflow nodes", "Responses", "Delivery and tracking events"],
        operations=["SMTP queue", "Playwright journeys", "Stripe seam", "PDF and Excel export"],
        evidence=["README.md", "nps_architecture_ceo.md", "web-app/src/db/schema.ts", "web-app/src/lib/nps/engine.ts", "web-app/src/lib/workflow/"],
        controls=["Token-scoped response access", "Validated workflow transitions", "Internal deployment details removed", "No AI overclaim"],
    ),
    p(
        slug="newsnext", name="NewsNext Semantic News Intelligence", archive="Newsnext.zip",
        category="Data & decision intelligence", level="deterministic",
        summary="A zero-dependency news aggregation and personalization service with semantic image matching, trust controls and digest workflows.",
        ai_role="Local feature hashing, n-grams, cosine similarity, entity extraction and taxonomy scoring provide semantic ranking without an LLM runtime.",
        stack=["Node.js", "JavaScript", "SQLite", "Playwright", "n8n", "RSS / Atom", "SMTP"],
        skills=["Semantic retrieval", "Feature hashing", "Feed ingestion", "Taxonomy design", "Caching", "Content governance"],
        flow=["RSS and digest sources", "Parser and normalizer", "Entity and taxonomy engine", "Semantic image ranker", "SQLite cache", "Authenticated dashboard"],
        services=["Feed ingestor", "Semantic image engine", "Digest webhook", "OTP and session service"],
        ai=["Feature-hash vectors", "Cosine similarity", "Hybrid relevance ranking", "Recurring-entity learning"],
        data=["Normalized stories", "Taxonomy metadata", "Image descriptors", "Telemetry and preferences"],
        operations=["n8n webhooks", "SMTP OTP", "Playwright checks", "Zero-dependency HTTP server"],
        evidence=["IMAGE-ENGINE.md", "lib/image-engine/text.js", "lib/image-engine/engine.js", "lib/image-engine/taxonomy.js", "lib/rss.js", "lib/db.js"],
        controls=["Demo secrets removed", "Internal identities neutralized", "Unlicensed images excluded", "Source-trust metadata"],
    ),
    p(
        slug="netsuite-token-service", name="NetSuite OAuth Token & Wrapper Service", archive="NetSuiteToken.zip",
        category="Enterprise operations", level="deterministic",
        summary="A .NET service for RSA-PSS client assertions, OAuth token exchange and controlled NetSuite API integration.",
        ai_role="No AI capability is implemented; the technical value is secure enterprise authentication and integration design.",
        stack=["C#", ".NET 8", "ASP.NET Core", "JWT", "RSA-PSS", "Swagger", "Docker"],
        skills=["OAuth client assertions", "JWT signing", "Certificate handling", "API integration", "Dependency injection", "Security hardening"],
        flow=["Authorized caller", "Token controller", "Key and configuration", "Signed JWT assertion", "NetSuite OAuth", "Bounded API call"],
        services=["Token controller", "Configuration helper", "JWT signing service", "API wrapper"],
        ai=["No runtime AI", "Deterministic OAuth protocol"],
        data=["Non-secret configuration", "Short-lived access token", "API request and response"],
        operations=["ASP.NET Core", "Kestrel", "Docker", "Swagger"],
        evidence=["NetsuiteAPI/Services/TokenService.cs", "NetsuiteAPI/NetSuiteConfigurationHelper.cs", "NetsuiteAPI/Controllers/HomeController.cs", "NetsuiteAPI/Program.cs"],
        controls=["Bundled certificate and keys excluded", "Credential rotation required", "Destination allowlist required", "Application authentication required"],
    ),
    p(
        slug="nemoclaw-revops", name="NEMOCLAW RevOps Intelligence", archive="NEMOCLAWFORMY.zip",
        category="Agentic AI & automation", level="prototype",
        summary="A multi-agent revenue-operations platform for natural-language analytics, opportunity intelligence, research and executive reporting.",
        ai_role="LangGraph coordinates NL-to-SQL, research, portfolio and reporting agents using hosted or local models, semantic cache and self-correcting execution.",
        stack=["Python", "FastAPI", "LangGraph", "LangChain", "Chroma", "SentenceTransformers", "SQLite", "React"],
        skills=["Agent orchestration", "NL-to-SQL", "Semantic caching", "Provider failover", "Scheduled agents", "Executive reporting"],
        flow=["CRM and Redash", "Ingestion and cache", "SQLite and Chroma", "Schema-aware planner", "Specialized agent DAG", "Reports and alerts"],
        services=["Ingestion service", "SQL engine", "LangGraph orchestrator", "Report and alert APIs"],
        ai=["Cerebras-compatible LLM", "Local Qwen fallback", "NL-to-SQL retry", "Semantic memory"],
        data=["Sanitized CRM model", "SQLite analytical cache", "Chroma memory", "Report store"],
        operations=["FastAPI", "APScheduler", "Local inference", "React dashboard"],
        evidence=["backend/main.py", "backend/orchestrator.py", "backend/llm_client.py", "backend/data_ingestion.py", "backend/sqlite_engine.py", "backend/agents/"],
        controls=["Embedded source credential removed", "Read-only database connection required", "API authentication required", "Internal schema and endpoints excluded"],
    ),
    p(
        slug="mprbot", name="MPR Support Intelligence Hub", archive="MPRBOT-1.zip",
        category="Knowledge, RAG & document AI", level="prototype",
        summary="A support intelligence workspace combining historical cases, operating procedures and hybrid retrieval for recommendations and diagnostics.",
        ai_role="BGE embeddings, FAISS, BM25 and a cross-encoder retrieve and rerank evidence before hosted or local Qwen generation, with feedback-aware scoring.",
        stack=["Python", "FastAPI", "FAISS", "SentenceTransformers", "BM25", "llama.cpp", "Next.js", "PostgreSQL"],
        skills=["Hybrid RAG", "Cross-encoder reranking", "Case-pair extraction", "Provider failover", "Feedback loops", "Support analytics"],
        flow=["Cases and SOPs", "Cleaning and pairing", "FAISS and BM25", "Cross-encoder rerank", "Contextual LLM", "Recommendation and feedback"],
        services=["Case processor", "Hybrid retriever", "Recommendation API", "Support dashboard"],
        ai=["BGE embeddings", "BM25 retrieval", "MiniLM reranker", "Hosted and local Qwen"],
        data=["Synthetic case pairs", "SOP chunks", "Rebuilt vector index", "Feedback events"],
        operations=["FastAPI", "Next.js", "Docker", "Azure pipeline"],
        evidence=["services/agent.py", "services/llm_provider.py", "services/retriever.py", "services/indexer.py", "services/reranker.py", "backend_api/app/routers/search.py"],
        controls=["All credentials removed", "Cases and SOP documents excluded", "Plaintext user store excluded", "Prototype limitations disclosed"],
    ),
    p(
        slug="kb-preproduction", name="AIbot RAG API — Preproduction", archive="KB_Preproduction.zip",
        category="Knowledge, RAG & document AI", level="implemented",
        summary="A channel-ready retrieval service with Milvus search, reranking, streaming generation, session memory and trace instrumentation.",
        ai_role="MiniLM embeddings retrieve from Milvus, a reranker orders evidence and hosted or local generation returns source-backed answers over SSE or JSON.",
        stack=["Python", "FastAPI", "Milvus", "SentenceTransformers", "Groq", "llama.cpp", "OpenTelemetry", "Docker"],
        skills=["RAG microservices", "Vector search", "Reranking", "Streaming APIs", "Session memory", "LLM observability"],
        flow=["UI and channel request", "FastAPI", "Query embedding", "Milvus retrieval", "Rerank and prompt", "Streamed cited answer"],
        services=["RAG API", "Retriever", "Generator", "Session and webhook adapters"],
        ai=["MiniLM embedding", "Milvus similarity search", "Reranker", "Groq or local generation"],
        data=["Sanitized chunk contract", "Milvus collection", "Session context", "Source metadata"],
        operations=["SSE", "Phoenix and OpenTelemetry", "Docker", "Channel webhooks"],
        evidence=["app/services/rag_pipeline.py", "app/services/retriever.py", "app/services/generator.py", "llm/providers/chat_client.py", "vector_store/queries.py"],
        controls=["Exported vector corpus excluded", "Embedded API key removed", "Endpoint authentication required", "Prompt traces minimized"],
    ),
    p(
        slug="kb-prod", name="AIbot Production RAG API", archive="KB PROD.zip",
        category="Knowledge, RAG & document AI", level="prototype",
        summary="A backend RAG service decomposition for embedding, Milvus retrieval, reranking, model generation and telemetry.",
        ai_role="The archived services implement the core RAG pipeline, but missing imported routes and the referenced root application prevent a verified runnable claim.",
        stack=["Python", "FastAPI", "Milvus", "SentenceTransformers", "llama.cpp", "OpenTelemetry", "Docker"],
        skills=["RAG service boundaries", "Vector retrieval", "Provider abstraction", "Telemetry", "Deployment packaging", "Gap analysis"],
        flow=["Client request", "Incomplete API shell", "Query embedding", "Milvus retrieval", "Rerank and generation", "Answer with sources"],
        services=["Intended API layer", "RAG pipeline", "Retriever", "Provider client"],
        ai=["Sentence embeddings", "Milvus retrieval", "Reranking", "Hosted or local generation"],
        data=["Milvus vectors", "Session context", "Source metadata"],
        operations=["FastAPI", "Docker", "Phoenix and OpenTelemetry", "Incomplete route bundle"],
        evidence=["app/services/rag_pipeline.py", "app/services/retriever.py", "llm/providers/chat_client.py", "vector_store/"],
        controls=["Incomplete archive label", "No runnable claim", "Internal topology removed", "Authentication required before deployment"],
    ),
    p(
        slug="btkb", name="Zeno Enterprise Knowledge Assistant", archive="KB.zip",
        category="Knowledge, RAG & document AI", level="implemented",
        summary="An enterprise knowledge assistant with ACL-aware hybrid retrieval, confidence refusal, streaming answers, OTP access and production observability.",
        ai_role="Dense and BM25 retrieval are fused and reranked before guarded model generation; ACL and confidence gates decide whether context may be used or the system must refuse.",
        stack=["Python", "FastAPI", "LlamaIndex", "Milvus", "Redis", "PostgreSQL", "Next.js", "Kubernetes"],
        skills=["Production RAG", "ACL-aware retrieval", "Reciprocal-rank fusion", "Guardrails", "Streaming UX", "Observability"],
        flow=["Authenticated portal", "Input guard", "Dense and BM25 retrieval", "RRF and rerank", "ACL and confidence gate", "Streamed cited answer"],
        services=["OTP and team context", "RAG API", "Retrieval and reflection", "History and administration"],
        ai=["Qwen embeddings and reranking", "Groq generation", "ReAct and optional HyDE", "Reflection and hallucination checks"],
        data=["External corpus contract", "Milvus vectors", "Redis cache", "PostgreSQL history"],
        operations=["SSE", "Phoenix", "Prometheus", "Kubernetes and Jenkins"],
        evidence=["backend/retrieval/retrieval.py", "backend/retrieval/agentic_rag.py", "backend/retrieval/self_reflection.py", "backend/app/llm_client.py", "backend/app/guardrails.py"],
        controls=["Identity and ACL datasets excluded", "ACL before generation", "Confidence refusal", "Output credential scrubbing"],
    ),
    p(
        slug="it-initiative", name="IT Initiative", archive="IT Initiative.zip",
        category="Concept / source unavailable", level="concept",
        summary="The supplied archive contains only a generic project-template README and no verifiable implementation.",
        ai_role="No application, model, agent, data contract or deployment evidence is available; diagrams identify the evidence gap rather than inventing a system.",
        stack=["Source unavailable"], skills=["No verifiable technical skills in supplied archive"],
        flow=["Initiative intent", "Missing source", "Problem definition", "Architecture proposal", "Implementation", "Verification"],
        services=["Implementation not supplied"], ai=["No runtime AI evidenced"], data=["No data model supplied"], operations=["No deployment evidence supplied"],
        evidence=["README.md"], controls=["Concept label", "No fabricated claims", "No runnable status claim", "Request complete source"],
    ),
    p(
        slug="ideastorm", name="IdeaStorm AI Opportunity & Agent Governance", archive="Ideastorm.zip",
        category="Agentic AI & automation", level="implemented",
        summary="An enterprise idea-to-outcome platform with AI triage, duplicate detection, governed agents, human review, POC tracking and ROI evidence.",
        ai_role="A scheduler and event plane coordinate specialized agents behind policy, budget, guardrail and kill-switch gates, with deterministic fallback and human approval.",
        stack=["React", "TypeScript", "Vite", "Fastify", "PostgreSQL", "Playwright", "JWT", "Agent SDK"],
        skills=["Agent governance", "Human-in-the-loop", "Policy and budget gates", "Run tracing", "Event orchestration", "Outcome measurement"],
        flow=["Idea portal", "Idea service", "PostgreSQL and event bus", "Policy-gated agent runtime", "AI proposal", "Human review and outcome"],
        services=["Idea intake", "Triage and scoring", "Agent Control Tower", "POC and outcome service"],
        ai=["Specialized agent handlers", "On-prem model adapter", "TF-IDF duplicate detection", "Reflection and skills"],
        data=["Ideas and evaluations", "Agent run ledger", "Policies and budgets", "Outcomes and ROI"],
        operations=["Scheduler and webhooks", "Kill switches", "Incident workflow", "Playwright tests"],
        evidence=["server/src/agents.ts", "server/src/agent-scheduler.ts", "server/src/llm.ts", "server/src/agent-reflection.ts", "server/src/bn-agents.ts", "packages/agent-sdk/"],
        controls=["Corporate hierarchy data excluded", "Policy and budget preflight", "Kill switch and incident path", "Human approval before consequential actions"],
    ),
    p(
        slug="hr-agent", name="HR Agent", archive="HRAGENT.zip",
        category="Concept / source unavailable", level="concept",
        summary="The supplied archive contains a generic README and a workstation sync script, but no HR application or agent implementation.",
        ai_role="No model, orchestration, HR data contract, evaluation or interface can be verified from the supplied evidence.",
        stack=["Source unavailable"], skills=["No verifiable implementation in supplied archive"],
        flow=["HR use-case intent", "Missing source", "Privacy requirements", "Agent design", "Implementation", "Bias and quality evaluation"],
        services=["Implementation not supplied"], ai=["No runtime AI evidenced"], data=["No HR data model supplied"], operations=["Local sync script excluded"],
        evidence=["README.md", ".git_sync.sh"], controls=["Concept label", "Employee privacy required", "Local path removed", "No implementation claims"],
    ),
    p(
        slug="delivery-command-center", name="Delivery Command Center", archive="Delivery Command Center.zip",
        category="Data & decision intelligence", level="prototype",
        summary="A leadership portfolio cockpit combining delivery, revenue, case, risk and action evidence with grounded AI signals and rule-based fallback.",
        ai_role="Compact aggregate facts are sent to a model for strict-JSON alerts, nudges and insights; normalization and deterministic rules keep the factual baseline authoritative.",
        stack=["Python", "FastAPI", "SQLAlchemy", "PostgreSQL", "React", "TypeScript", "OpenAI API", "Docker"],
        skills=["Portfolio analytics", "Data lineage", "Grounded insight generation", "Fallback rules", "Executive visualization", "API design"],
        flow=["CRM and supplementary sources", "SQL aggregation", "Portfolio API", "Factual digest", "Model or rules", "Dashboard signals"],
        services=["Portfolio service", "Facet APIs", "Signal engine", "Executive dashboard"],
        ai=["Strict-JSON signal generation", "Grounded portfolio digest", "Deterministic risk fallback"],
        data=["Sanitized project metrics", "Revenue and case aggregates", "Governance actions", "Signal payload"],
        operations=["FastAPI", "PostgreSQL", "React build", "Docker"],
        evidence=["backend/project_intel/services/command_centre_v2_service.py", "backend/project_intel/services/command_centre_v2_signals.py", "backend/project_intel/project_lifecycle.py", "backend/main.py"],
        controls=["Customer and project data excluded", "Destructive seed route excluded", "Validated structured outputs", "Authentication and restricted CORS required"],
    ),
    p(
        slug="deal-intelligence", name="Deal Intelligence", archive="Dealintelligence.zip",
        category="Concept / source unavailable", level="concept",
        summary="This specific archive contains only a generic README; it does not include the deal-intelligence implementation found in a separate bundle.",
        ai_role="No code or technical evidence can be attributed to this archive. The separate Agentic Harness package is assessed independently to avoid conflating sources.",
        stack=["Source unavailable"], skills=["No verifiable technical skills in supplied archive"],
        flow=["Deal use-case intent", "Missing source", "Evidence contract", "Pipeline design", "Implementation", "Evaluation"],
        services=["Implementation not supplied"], ai=["No runtime AI evidenced in this archive"], data=["No deal data model supplied"], operations=["No deployment evidence supplied"],
        evidence=["README.md"], controls=["Concept label", "Separate archives not conflated", "No model claims", "Request complete source"],
    ),
    p(
        slug="dbprod", name="DBProd Governed Analytics Copilot", archive="DBProd.zip",
        category="Agentic AI & automation", level="implemented",
        summary="A governed natural-language analytics copilot built around typed semantic plans, deterministic SQL compilation, bounded model advice and evidence-gated learning.",
        ai_role="Retrieval and a bounded advisor may select from safe semantic candidates, but every proposal returns through typed compilation, ownership policy and read-only SQL controls.",
        stack=["Python", "PostgreSQL", "Redash", "scikit-learn", "SentenceTransformers", "SSE", "Docker", "Caddy"],
        skills=["Secure text-to-SQL", "Semantic layers", "Model authority boundaries", "Learning governance", "Schema drift", "Release evidence"],
        flow=["Natural-language question", "Semantic catalog retrieval", "Bounded model advisor", "Typed SQL compiler", "Security gates and Redash", "Masked answer or learning job"],
        services=["Query Studio", "Semantic planner", "Security policy", "Learning and capability lifecycle"],
        ai=["TF-IDF retrieval", "Optional dense retrieval", "Bounded Gemma advisor", "Evidence-gated learning"],
        data=["Semantic catalog", "Typed intermediate representation", "PostgreSQL learning store", "Signed artifacts"],
        operations=["SSO", "Audit stream", "Caddy and Docker", "Jenkins and rollback"],
        evidence=["work/redash_schema/query_studio.py", "work/redash_schema/semantic_ir.py", "work/redash_schema/semantic_search.py", "work/redash_schema/security_policy.py", "work/redash_schema/learning_service.py"],
        controls=["Deterministic compiler is authoritative", "Read-only and bounded SQL", "Owner and catalog validation", "Internal topology removed"],
    ),
    p(
        slug="dbbot", name="Autonomous AI SQL Assistant", archive="DBBOT.zip",
        category="Agentic AI & automation", level="prototype",
        summary="A conversational CRM and ERP analytics assistant with intent routing, schema retrieval, guarded SQL generation, result narration and MCP tools.",
        ai_role="Provider-routed LLMs classify intent, plan and generate SQL or functions; deterministic direct paths, retrieval and SQL guards constrain execution.",
        stack=["Node.js", "Express", "React", "Vite", "PostgreSQL", "Groq", "NVIDIA NIM", "MCP"],
        skills=["Multi-provider inference", "Text-to-SQL", "Schema retrieval", "MCP tooling", "Provider failover", "Query safety"],
        flow=["Conversational query", "Intent router", "Direct path or catalog retrieval", "SQL agent", "Validation and PostgreSQL", "Analyst narrative"],
        services=["Express query API", "Intent and retrieval agents", "SQL and analyst agents", "MCP server"],
        ai=["Groq and NVIDIA models", "Local Ollama fallback", "Planner and SQL agents", "Hermes error memory"],
        data=["Sanitized schema catalog", "Stored-procedure metadata", "Read-only query result", "Learning memory"],
        operations=["Express", "React dashboard", "MCP interface", "Rate and timeout middleware"],
        evidence=["backend/routes/query.js", "backend/agents/intentClassifier.js", "backend/agents/retrievalAgent.js", "backend/agents/sqlAgent.js", "backend/utils/providerManager.js", "backend/mcpServer.js"],
        controls=["Both environment files excluded", "API and database credentials rotated", "Generated catalogs and traces excluded", "Read-only SQL enforcement required"],
    ),
    p(
        slug="datamart-dwh", name="Autonomous AI Data Stack", archive="DATAMART-DWH.zip",
        category="Data & decision intelligence", level="prototype",
        summary="A warehouse and natural-language analytics prototype that transforms operational CRM data into dimensional models and interactive analysis.",
        ai_role="NVIDIA and Gemini adapters generate SQL, summaries and chart choices over an introspected warehouse; the current direct-execution path requires stronger SQL controls.",
        stack=["Python", "PostgreSQL", "pandas", "Streamlit", "Plotly", "Flask", "NVIDIA NIM", "Gemini"],
        skills=["Data warehousing", "ETL", "Dimensional modeling", "NL-to-SQL", "Analytical UX", "Deployment automation"],
        flow=["Operational CRM", "Python rebuild ETL", "Bronze and silver models", "Schema introspection", "LLM-generated SQL", "Chart and narrative"],
        services=["ETL runner", "Warehouse schema", "Natural-language dashboard", "Chart and summary layer"],
        ai=["NVIDIA text-to-SQL", "Gemini text-to-SQL", "LLM summarization", "Chart specification"],
        data=["Operational extracts", "Dimensions and facts", "Semantic metadata", "Query result frames"],
        operations=["Streamlit", "Flask sync seam", "Remote deployment scripts excluded", "PostgreSQL"],
        evidence=["run_dwh_etl.py", "deploy_dashboard_nvidia.py", "deploy_dashboard_nlp.py", "dwh_setup.py", "autonomous_ai_data_stack.md"],
        controls=["All infrastructure credentials rotated", "Read-only AST validation required", "Destructive rebuild isolated", "Unauthenticated sync disabled"],
    ),
    p(
        slug="crm-data-audit", name="CRM Data Audit Framework", archive="Data Audit Framework.zip",
        category="Data & decision intelligence", level="deterministic",
        summary="A modular CRM data-quality cockpit with transparent SQL rules, KPI summaries, prioritized issues and record-level drilldowns.",
        ai_role="No LLM is implemented. Audits are deterministic SQL, thresholds and metrics with a mock/live execution boundary.",
        stack=["Node.js", "PostgreSQL", "React", "TypeScript", "Vite", "Tailwind", "SVG charts"],
        skills=["Data-quality rules", "Modular audit architecture", "Custom database protocol", "Drilldown UX", "Mock/live parity", "KPI design"],
        flow=["CRM PostgreSQL", "Audit module registry", "Deterministic SQL executor", "KPI and issue model", "Audit API", "Dashboard drilldown"],
        services=["Module registry", "Audit executor", "Opportunity and user modules", "React dashboard"],
        ai=["No runtime AI", "Transparent rule evaluation", "Deterministic mock executor"],
        data=["CRM records", "Audit results", "KPI summaries", "Issue drilldowns"],
        operations=["Node HTTP service", "React build", "PostgreSQL or mock mode", "Module rollout"],
        evidence=["crm-audit/server/index.js", "crm-audit/server/registry.js", "crm-audit/server/modules/opportunity.js", "crm-audit/server/modules/users.js", "crm-audit/web/src/components/AuditDashboard.tsx"],
        controls=["No AI overclaim", "Internal database topology removed", "Restricted CORS required", "Rule lineage remains visible"],
    ),
    p(
        slug="consentnext", name="ConsentNext Governance Platform", archive="Consent Management.zip",
        category="Governance, risk & security", level="implemented",
        summary="A multi-tenant consent and preference platform with signed append-only evidence, maker-checker governance and reliable downstream propagation.",
        ai_role="Risk monitoring is deterministic and explainable rather than model-based, using rules and anomaly scores over governed consent-ledger read models.",
        stack=["FastAPI", "SQLAlchemy", "PostgreSQL", "Next.js", "React", "Kafka", "RabbitMQ", "OIDC"],
        skills=["Domain-driven design", "Cryptographic ledgers", "Transactional outbox", "Tenant isolation", "Maker-checker workflows", "Regulatory evidence"],
        flow=["Consent channel", "Identity and policy validation", "Signed append-only version", "Audit and outbox", "Kafka or RabbitMQ", "Downstream read models"],
        services=["Consent aggregate", "Governance workflow", "Evidence and audit", "Connector orchestration"],
        ai=["No model inference", "Deterministic anomaly scoring", "Explainable compliance rules"],
        data=["Consent versions", "Evidence receipts", "Audit ledger", "Outbox and read models"],
        operations=["OIDC and RBAC", "KMS seam", "Kafka and RabbitMQ", "Docker and migrations"],
        evidence=["consentnext/ARCHITECTURE.md", "consentnext/backend/app/modules/consent/", "consentnext/backend/app/modules/integration/", "consentnext/backend/app/modules/governance/", "consentnext/backend/app/platform/kms.py"],
        controls=["Insert-only signed versions", "Tenant and purpose isolation", "Maker-checker approval", "Licensed assets and internal specs excluded"],
    ),
    p(
        slug="clm-ocr-rag", name="Contract OCR & Local RAG", archive="CLMOCR.zip",
        category="Knowledge, RAG & document AI", level="implemented",
        summary="A private contract-intelligence pipeline for OCR, hybrid retrieval, local generation, citations, summaries and obligation extraction.",
        ai_role="OCR and digital extraction feed dense and BM25 retrieval, cross-encoder reranking and local Qwen generation with source citations.",
        stack=["Python", "FastAPI", "Tesseract", "pdfplumber", "Chroma", "BM25", "SentenceTransformers", "llama.cpp"],
        skills=["Document OCR", "Hybrid RAG", "Cross-encoder reranking", "Citation grounding", "Local inference", "Contract analytics"],
        flow=["PDF or image", "Digital extraction or OCR", "Chunk and metadata pipeline", "Chroma and BM25", "Cross-encoder rerank", "Local cited answer"],
        services=["OCR router", "Ingestion service", "Hybrid retriever", "Generation and citation API"],
        ai=["Tesseract OCR", "Sentence embeddings", "Cross-encoder reranker", "Local Qwen generation"],
        data=["Synthetic document contract", "Chunk metadata", "Rebuilt search indexes", "Citation and obligation results"],
        operations=["FastAPI", "Local CPU or GPU", "Static web UI", "Word export"],
        evidence=["app/ocr/ocr_pipeline.py", "app/ingest/ingest_service.py", "app/retrieval/retriever.py", "app/rag/generate.py", "app/rag/cite.py", "app/main.py"],
        controls=["All customer contracts excluded", "OCR cache and indexes excluded", "Local inference boundary", "Citations tied to retrieved chunks"],
    ),
    p(
        slug="biztech-command-center", name="BizTech Operations Command Center", archive="Biztech_Command_center.zip",
        category="Data & decision intelligence", level="implemented",
        summary="A unified engineering, delivery, OKR, profitability, resource and incident cockpit with deterministic signals and optional AI explanation.",
        ai_role="Core metrics and recommendations are deterministic; optional model adapters rewrite evidence-backed language or answer operational questions without changing source facts.",
        stack=["React", "TypeScript", "Vite", "Recharts", "Python", "Node.js", "Azure DevOps", "Redash"],
        skills=["Multi-source analytics", "KPI engineering", "Recommendation validation", "RBAC", "Operational UX", "Static publishing"],
        flow=["Enterprise sources", "Python normalization", "Typed JSON contracts", "Deterministic signal engine", "Optional AI wording", "Command-center dashboards"],
        services=["Source fetchers", "Signal generator", "IntelBot and LLM hooks", "React dashboard and RBAC API"],
        ai=["Evidence-preserving rewrites", "Rule-based IntelBot", "Optional local model fallback", "Hermes feedback memory"],
        data=["Sanitized metric contracts", "Portfolio measures", "Alert evidence", "RBAC state"],
        operations=["Static web build", "Node RBAC API", "Scheduled source refresh", "Test suite"],
        evidence=["src/App.tsx", "src/hooks/useIntelBot.js", "src/hooks/useLLM.js", "scripts/generate_recommendations.py", "rbac-api/"],
        controls=["All operational datasets excluded", "Legacy auth proxy excluded", "Evidence restored after AI rewrite", "Restricted CORS and Entra required"],
    ),
    p(
        slug="biztech-enterprise", name="BizTech Enterprise Data & Automation Repository", archive="BizTech.zip",
        category="Enterprise operations", level="deterministic",
        summary="A broad enterprise SQL, migration, reporting, RevOps and BizOps engineering repository with selected dashboard automation.",
        ai_role="The core corpus is deterministic database and operations engineering; optional assistant features exist only in selected dashboard components.",
        stack=["SQL Server", "PostgreSQL", "T-SQL", "PL/pgSQL", "Python", "React", "Azure DevOps", "Reporting Services"],
        skills=["Enterprise SQL", "Database migration", "Financial reporting", "RevOps analytics", "CI promotion", "Operational governance"],
        flow=["Operational databases", "Stored procedures and ETL", "Migration and validation", "Reporting data marts", "Operational dashboards", "Governed promotion"],
        services=["SQL procedure corpus", "Migration tooling", "Report definitions", "Embedded command center"],
        ai=["Mostly non-AI", "Optional dashboard assistant", "Deterministic reporting logic"],
        data=["Synthetic schema excerpts", "Representative query contracts", "Report metadata", "No production backup content"],
        operations=["Azure pipelines", "SQL deployment", "Documentation generation", "Dashboard publishing"],
        evidence=["README.md", "StoredProcedures/README.md", "PGMigration/README.md", "Revops/README.md", "Bizops/README.md", "biztech-dashboard/"],
        controls=["Database backups excluded", "Production procedure corpus minimized", "Customer documents and datasets excluded", "Representative source only"],
    ),
    p(
        slug="alerting-framework", name="Alerting Framework", archive="alertingframework.zip",
        category="Concept / source unavailable", level="concept",
        summary="The supplied archive contains only a generic README and no alerting service, rules, integrations or AI implementation.",
        ai_role="No model, detection logic, routing workflow, data contract or runtime evidence is available for verification.",
        stack=["Source unavailable"], skills=["No verifiable technical skills in supplied archive"],
        flow=["Alerting intent", "Missing source", "Signal contract", "Detection and routing design", "Implementation", "SLO validation"],
        services=["Implementation not supplied"], ai=["No runtime AI evidenced"], data=["No signal model supplied"], operations=["No deployment evidence supplied"],
        evidence=["README.md"], controls=["Concept label", "No fabricated implementation", "No runtime claim", "Request complete source"],
    ),
    p(
        slug="ai-testing-bizvalidate", name="BizValidate Agentic Quality Platform", archive="AITESTING.zip",
        category="AI testing & quality", level="implemented",
        summary="An AI-assisted web and API validation platform spanning browser journeys, DOM and accessibility analysis, HAR evidence, visual regression and selector healing.",
        ai_role="A bounded model classifies elements, proposes selectors and tests, analyzes failures and supports healing while Playwright and deterministic validators own execution and evidence.",
        stack=["Python", "FastAPI", "SQLAlchemy", "PostgreSQL", "Playwright", "Next.js", "React", "WebSockets"],
        skills=["AI-assisted QA", "Browser automation", "Self-healing selectors", "HAR analysis", "Visual regression", "Experimentation"],
        flow=["Test configuration", "Encrypted credential seam", "Playwright run", "DOM AX HAR discovery", "LLM enrichment", "Evidence and results"],
        services=["Run pipeline", "Playwright engine", "DOM and HAR analyzers", "Healing and autoresearch"],
        ai=["Element classification", "Selector and test proposals", "Failure analysis", "Prompt-selection experiments"],
        data=["Synthetic test configuration", "DOM and accessibility evidence", "HAR metadata", "Result history"],
        operations=["FastAPI queue", "WebSockets and SSE", "Next.js dashboard", "PostgreSQL"],
        evidence=["backend/app/services/pipeline.py", "backend/app/services/playwright_engine.py", "backend/app/services/dom_analyzer.py", "backend/app/services/llm_service.py", "backend/app/services/healing_engine.py", "backend/app/autoresearch/"],
        controls=["Hard-coded model credential removed and rotated", "Bundled model excluded", "Default admin disabled", "Evidence sanitized and encrypted"],
    ),
    p(
        slug="agentic-harness", name="Agentic Harness & Deal Intelligence Lab", archive="Agentic Harness.zip",
        category="Agentic AI & automation", level="prototype",
        summary="A multimodal conversation-intelligence and workflow lab with transcription, diarization, retrieval, deal scoring, visual context and n8n orchestration.",
        ai_role="Speech, speaker, embedding, retrieval, vision and hosted/local language models refine deterministic MEDDICC and BANT scoring into an evidence-backed deal analysis.",
        stack=["Python", "Streamlit", "n8n", "Chroma", "SentenceTransformers", "Parakeet", "pyannote", "OpenCV"],
        skills=["Conversation intelligence", "Multimodal processing", "RAG", "Deal methodology scoring", "Provider abstraction", "Workflow orchestration"],
        flow=["Video audio and documents", "ASR diarization and OCR", "Transcript chunking", "Vector retrieval", "Deal scoring and LLM refinement", "Dashboard and workflow actions"],
        services=["Media pipeline", "Vector store", "Scoring and refinement", "Streamlit and n8n surfaces"],
        ai=["Parakeet transcription", "pyannote diarization", "Chroma retrieval", "Hosted and local model adapters"],
        data=["Synthetic transcript chunks", "Vector representations", "Score evidence", "Workflow state"],
        operations=["Streamlit", "n8n", "Docker Compose", "Monitoring command center"],
        evidence=["Deal Intelligence/dealintel/pipeline.py", "Deal Intelligence/dealintel/llm.py", "Deal Intelligence/dealintel/scoring.py", "Deal Intelligence/app/streamlit_app.py", "N8N Command Center/server.js"],
        controls=["Workflow credential token removed and rotated", "Contributor and customer artifacts excluded", "Proprietary media and documents excluded", "Human-owned deal decisions"],
    ),
]


# Portfolio navigation metadata is deliberately separate from the source-review
# classification above.  It changes how the public library is explored; it does
# not change or inflate the evidence available for any project.
FLAGSHIP_SLUGS = (
    "ideastorm",
    "zeno-injector",
    "consentnext",
    "ai-testing-bizvalidate",
    "dbprod",
    "btkb",
    "wsr-automate",
    "clm-ocr-rag",
)

FAMILY_BY_SLUG = {
    "zeno-injector": "Zeno & enterprise knowledge",
    "kb-preproduction": "Zeno & enterprise knowledge",
    "kb-prod": "Zeno & enterprise knowledge",
    "btkb": "Zeno & enterprise knowledge",
    "rmg-bot": "RMG & workforce planning",
    "rmg-budgeting": "RMG & workforce planning",
    "rmg-project360": "RMG & workforce planning",
    "skill-management": "RMG & workforce planning",
    "hr-agent": "RMG & workforce planning",
    "profitability": "BizTech decision systems",
    "oneview": "BizTech decision systems",
    "okr-dashboard": "BizTech decision systems",
    "us-project-health": "BizTech decision systems",
    "delivery-command-center": "BizTech decision systems",
    "biztech-command-center": "BizTech decision systems",
    "biztech-enterprise": "BizTech decision systems",
    "dbprod": "Database & analytics copilots",
    "dbbot": "Database & analytics copilots",
    "datamart-dwh": "Database & analytics copilots",
    "crm-data-audit": "Database & analytics copilots",
    "whatsapp-bot-monitoring": "Quality & monitoring",
    "world-monitor": "Quality & monitoring",
    "alerting-framework": "Quality & monitoring",
    "ai-testing-bizvalidate": "Quality & monitoring",
}

DECISION_EVIDENCE_BY_SLUG = {
    "ideastorm": [
        "Policy and budget preflight precede agent execution.",
        "Consequential actions remain behind human approval, a kill switch and an incident path.",
    ],
    "zeno-injector": [
        "ACL metadata is preserved through ingestion and vector persistence.",
        "Embedding contracts, delete guards and a recovery ledger bound repeatable ingestion.",
    ],
    "consentnext": [
        "Consent evidence uses insert-only signed versions rather than mutable history.",
        "Tenant/purpose isolation and maker-checker approval gate governed changes.",
    ],
    "ai-testing-bizvalidate": [
        "Playwright and deterministic validators own execution; model proposals remain bounded inputs.",
        "Default administrative access is disabled and test evidence is sanitized and encrypted.",
    ],
    "dbprod": [
        "A deterministic typed compiler remains authoritative over bounded model advice.",
        "SQL is constrained by read-only, ownership, catalog and execution-boundary controls.",
    ],
    "btkb": [
        "ACL checks occur before generation, with confidence-based refusal when evidence is insufficient.",
        "Generated output passes through credential scrubbing before delivery.",
    ],
    "wsr-automate": [
        "Deterministic portfolio analysis is retained alongside structured model output repair.",
        "Source lineage and human-controlled distribution remain explicit delivery boundaries.",
    ],
    "clm-ocr-rag": [
        "The inference boundary stays local while dense and lexical retrieval are combined before reranking.",
        "Answer citations remain tied to retrieved chunks rather than model-only assertions.",
    ],
}


def _intelligence_type(project: dict) -> str:
    if project["evidence_level"] == "concept":
        return "Not established"
    if project["evidence_level"] == "deterministic":
        return "Deterministic / AI-enabling"
    if project["category"] == "Agentic AI & automation":
        return "Agentic AI"
    if project["category"] == "Knowledge, RAG & document AI":
        return "RAG / document AI"
    if project["category"] == "AI testing & quality":
        return "AI-assisted quality"
    return "AI-assisted intelligence"


for _project in PROJECTS:
    _level = _project["evidence_level"]
    _project["flagship"] = _project["slug"] in FLAGSHIP_SLUGS
    _project["family"] = FAMILY_BY_SLUG.get(_project["slug"], "Independent system")
    _project["capability"] = (
        "Concept / target state" if _level == "concept" else _project["category"]
    )
    _project["evidence_profile"] = {
        "source": "Documentation-only archive" if _level == "concept" else "Sanitized source samples",
        "verification": "Static review only · code not executed",
        "maturity": {
            "implemented": "Implementation archive",
            "prototype": "Prototype archive",
            "deterministic": "Deterministic implementation archive",
            "concept": "Concept / evidence gap",
        }[_level],
        "intelligence": _intelligence_type(_project),
    }
    _project["ownership_evidence"] = None
    _project["outcome_evidence"] = None
    _project["decision_evidence"] = DECISION_EVIDENCE_BY_SLUG.get(_project["slug"])
